### ISSUE TITLE
Entities are not eligible for Energy Dashboard

### ISSUE THREAD

**Issue by ZsBT** [ZsBT/hass-w1000-portal#1]
The entities created by this integration can not be added to Energy Dashboard.

**Comment by ZsBT** [comment]
I've found that from the integration, I cannot decide what kind of measurement the curve provides. Therefore, in Home Assistant, we need to create a template sensor manually as only the human knows what is behind the data.
For example, for the curve HU0XXXXX-1:1.8.0*0 , which is a strictly increasing value, create a helper like this:

```
- template:
    - sensor:
        - name: teljes energiafogyasztás
          unit_of_measurement: "kWh"
          state_class: total_increasing
          device_class: energy
          state: >
            {{ states("sensor.w1000_oraallas") | float }}

```
